import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import styles from '@/components/layout.module.scss';
import Menu from '@/components/menu';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Wanna wanna — the best small grocery list app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={styles.html}>
      <body className={[`${montserrat.variable} antialiased`, styles.body].join(' ')}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
